### ISSUE TITLE
Upgrade to use scroll API. Calling intercom.users.all() with many users causes BadRequestError

### ISSUE THREAD

**Issue by Tyler-Churchill** [intercom/python-intercom#186]
Trying to submit a bulk job to delete users and I am guessing I have too many users 

Specifically using ```intercom.users.all()```
received ```BadRequestError: page limit reached, please use scroll API```

EDIT: Actually, I am not even sure if bulk jobs are supported anymore? It seems like all API docs for it does not exist.

**Comment by dimitry-L** [comment]
You need to use 'intercom.users.scroll()' instead of 'intercom.users.all()'

**Comment by Tyler-Churchill** [comment]
I don't recall this functionality and documentation existing at the time I posted this. Closing!

**Comment by ex-nerd** [comment]
Might be worth updating the example in the main README to include this...
